version: "3.9"

services:
  traefik:
    image: traefik:2.9
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  srwedding-backend:
    image: srwedding-backend:latest
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "--port=5000"
      - "traefik.http.routers.srweddingbackend.rule=Host(`api.soffi-reza.wedding`)"
      - "traefik.http.routers.srweddingbackend.entrypoints=web"
      - "traefik.http.services.srweddingbackend.loadbalancer.server.port=5000"

  srwedding-frontend:
    image: srwedding-frontend:latest
    deploy:
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "--port=3000"
      - "traefik.http.routers.srweddingfrontend.rule=Host(`soffi-reza.wedding`)"
      - "traefik.http.routers.srweddingfrontend.entrypoints=web"
      - "traefik.http.services.srweddingfrontend.loadbalancer.server.port=3000"
