version: "3.9"

services:
  traefik:
    image: traefik:2.9
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  sr-wedding-backend:
    build:
      context: .
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.srwedding.rule=Host(`srwedding.com`)"
      - "traefik.http.routers.srwedding.entrypoints=web"
