name: Backend Deploy

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Create environment from secret
        run: echo '${{ secrets.BACKEND_ENV }}' > backend/.env
      - name: Build Backend
        run: docker build -t srwedding-backend ./backend
      - name: Copy docker compose file
        run: cp -r docker-compose.yml /home/ubuntu
      - name: Change directory to home
        run: cd /home/ubuntu
      - name: Run compose
        run: docker compose up -d --no-deps --build srwedding-backend
