name: Backend Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} cloud.canister.io:5000
      - name: Create environment from secret
        run: echo '${{ secrets.BACKEND_ENV }}' > backend/.env
      - name: Build Backend
        run: docker build -t cloud.canister.io:5000/fahmialfareza/srwedding-backend ./backend
      - name: Push to registry
        run: docker push cloud.canister.io:5000/fahmialfareza/srwedding-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Restart server
        run: >-
          curl --location --request POST 'https://api.github.com/repos/fahmialfareza/reverse-proxy-vps/dispatches' --header 'Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}' --header 'Accept: application/vnd.github.v3+json' --header 'Content-Type: application/json' --data-raw '{"event_type":"restart","client_payload":{"image":"cloud.canister.io:5000/fahmialfareza/srwedding-backend","service_name":"server_srwedding-backend"}}'
