name: Backend Deploy

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Create environment from secret
        run: echo '${{ secrets.BACKEND_ENV }}' > backend/.env
      - name: Copy files to server
        run: cp -r * .* /home/ubuntu/srwedding
      - name: Change directory to srwedding
        run: cd /home/ubuntu/srwedding
      - name: Run compose
        run: docker-compose up -d --no-deps --build backend
