name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u {{ secrets.DOCKER_USERNAME }} -p {{ secrets.DOCKER_PASSWORD }}
      # - name: Create environment from secret
      #   run: echo '${{ secrets.BACKEND_ENV }}' > backend/.env
      - name: Build Frontend
        run: docker build -t cloud.canister.io:5000/fahmialfareza/srwedding-frontend ./frontend
      - name: Push to registry
        run: docker push cloud.canister.io:5000/fahmialfareza/srwedding-frontend
      # - name: Copy docker compose file
      #   run: cp -r docker-compose.yml /home/ubuntu
      # - name: Change directory to home
      #   run: cd /home/ubuntu
      # - name: Run compose
      #   run: docker compose up -d --no-deps --build srwedding-frontend
