name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      # - name: Create environment from secret
      #   run: echo '${{ secrets.BACKEND_ENV }}' > backend/.env
      - name: Build Frontend
        run: docker build -t srwedding-frontend ./frontend
      - name: Copy docker compose file
        run: cp -r docker-compose.yml /home/ubuntu
      - name: Change directory to home
        run: cd /home/ubuntu
      - name: Run compose
        run: docker compose up -d --no-deps --build frontend
